[2022-04-12 12:48:47,407] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform3 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:47,565] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform3 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:47,569] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:47,572] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:48:47,574] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:47,680] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform3> on 2022-04-12 12:48:35.586771+00:00
[2022-04-12 12:48:47,702] {standard_task_runner.py:52} INFO - Started process 386 to run task
[2022-04-12 12:48:47,721] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform3', 'manual__2022-04-12T12:48:35.586771+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmphxeuxdof', '--error-file', '/tmp/tmpw1zt7alb']
[2022-04-12 12:48:47,742] {standard_task_runner.py:80} INFO - Job 75: Subtask transform3
[2022-04-12 12:48:48,237] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform3 manual__2022-04-12T12:48:35.586771+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:48:48,948] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:48:35.586771+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:48:35.586771+00:00
[2022-04-12 12:49:27,035] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (11,15,32,38,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 12:51:16,639] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 12:51:16,895] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform3, execution_date=20220412T124835, start_date=20220412T124847, end_date=20220412T125116
[2022-04-12 12:51:17,449] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 12:51:18,248] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
