[2022-04-11 13:54:58,978] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T13:54:53.008111+00:00 [queued]>
[2022-04-11 13:54:59,028] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T13:54:53.008111+00:00 [queued]>
[2022-04-11 13:54:59,032] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 13:54:59,034] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 13:54:59,036] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 13:54:59,122] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 13:54:53.008111+00:00
[2022-04-11 13:54:59,132] {standard_task_runner.py:52} INFO - Started process 4173 to run task
[2022-04-11 13:54:59,150] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T13:54:53.008111+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpprgnogwb', '--error-file', '/tmp/tmp0c_72_tj']
[2022-04-11 13:54:59,156] {standard_task_runner.py:80} INFO - Job 21: Subtask extract
[2022-04-11 13:54:59,440] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T13:54:53.008111+00:00 [running]> on host 474cd328f92b
[2022-04-11 13:54:59,751] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T13:54:53.008111+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T13:54:53.008111+00:00
[2022-04-11 13:56:50,958] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/try.py", line 35, in extract
    df = pd.read_csv(url, header=1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 4227
[2022-04-11 13:56:51,011] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=openDataETL, task_id=extract, execution_date=20220411T135453, start_date=20220411T135458, end_date=20220411T135651
[2022-04-11 13:56:51,087] {standard_task_runner.py:98} ERROR - Failed to execute job 21 for task extract (Error tokenizing data. C error: EOF inside string starting at row 4227; 4173)
[2022-04-11 13:56:51,211] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 13:56:51,355] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
