[2022-04-11 14:19:53,193] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:14:28.895377+00:00 [queued]>
[2022-04-11 14:19:53,332] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:14:28.895377+00:00 [queued]>
[2022-04-11 14:19:53,337] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:19:53,339] {taskinstance.py:1250} INFO - Starting attempt 2 of 3
[2022-04-11 14:19:53,345] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:19:53,481] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:14:28.895377+00:00
[2022-04-11 14:19:53,509] {standard_task_runner.py:52} INFO - Started process 5565 to run task
[2022-04-11 14:19:53,569] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:14:28.895377+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpod5wh91s', '--error-file', '/tmp/tmpaj8pmr28']
[2022-04-11 14:19:53,595] {standard_task_runner.py:80} INFO - Job 47: Subtask extract
[2022-04-11 14:19:54,097] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:14:28.895377+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:19:54,655] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:14:28.895377+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:14:28.895377+00:00
[2022-04-11 14:21:22,715] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-11 14:21:22,727] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 5565. PIDs of all processes in the group: [5565]
[2022-04-11 14:21:22,729] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5565
[2022-04-11 14:21:22,731] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-11 14:21:23,432] {process_utils.py:70} INFO - Process psutil.Process(pid=5565, status='terminated', exitcode=0, started='14:19:52') (5565) terminated with exit code 0
