[2022-04-12 12:48:46,691] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform2 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:46,929] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform2 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:46,931] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:46,933] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:48:46,935] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:47,038] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform2> on 2022-04-12 12:48:35.586771+00:00
[2022-04-12 12:48:47,056] {standard_task_runner.py:52} INFO - Started process 382 to run task
[2022-04-12 12:48:47,076] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform2', 'manual__2022-04-12T12:48:35.586771+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmprn7md3fk', '--error-file', '/tmp/tmpviz42h_f']
[2022-04-12 12:48:47,082] {standard_task_runner.py:80} INFO - Job 73: Subtask transform2
[2022-04-12 12:48:47,560] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform2 manual__2022-04-12T12:48:35.586771+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:48:48,127] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform2
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:48:35.586771+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:48:35.586771+00:00
[2022-04-12 12:49:27,230] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (11,15,32,38,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 12:51:30,932] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 12:51:31,096] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform2, execution_date=20220412T124835, start_date=20220412T124846, end_date=20220412T125131
[2022-04-12 12:51:31,450] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 12:51:31,792] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
