[2022-04-11 14:18:44,142] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:13:31.305288+00:00 [queued]>
[2022-04-11 14:18:44,178] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:13:31.305288+00:00 [queued]>
[2022-04-11 14:18:44,180] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:18:44,182] {taskinstance.py:1250} INFO - Starting attempt 2 of 3
[2022-04-11 14:18:44,183] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:18:44,226] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:13:31.305288+00:00
[2022-04-11 14:18:44,236] {standard_task_runner.py:52} INFO - Started process 5453 to run task
[2022-04-11 14:18:44,243] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:13:31.305288+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp_c_rbgo5', '--error-file', '/tmp/tmpo_8tnfqf']
[2022-04-11 14:18:44,246] {standard_task_runner.py:80} INFO - Job 36: Subtask extract
[2022-04-11 14:18:44,404] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:13:31.305288+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:18:44,575] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:13:31.305288+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:13:31.305288+00:00
[2022-04-11 14:20:16,487] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-11 14:20:16,582] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 5453. PIDs of all processes in the group: [5453]
[2022-04-11 14:20:16,587] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5453
[2022-04-11 14:20:16,596] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-11 14:20:17,651] {process_utils.py:70} INFO - Process psutil.Process(pid=5453, status='terminated', exitcode=0, started='14:18:43') (5453) terminated with exit code 0
