[2022-04-12 12:59:11,619] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:59:11,717] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:59:11,721] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:59:11,726] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:59:11,729] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:59:11,856] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform1> on 2022-04-12 12:55:27.121131+00:00
[2022-04-12 12:59:11,875] {standard_task_runner.py:52} INFO - Started process 940 to run task
[2022-04-12 12:59:11,920] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform1', 'manual__2022-04-12T12:55:27.121131+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmpj0vmwk0e', '--error-file', '/tmp/tmph12ajiuc']
[2022-04-12 12:59:11,936] {standard_task_runner.py:80} INFO - Job 77: Subtask transform1
[2022-04-12 12:59:12,465] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:55:27.121131+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:59:12,884] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform1
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:55:27.121131+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:55:27.121131+00:00
[2022-04-12 12:59:52,433] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (10,14,31,37,39,40) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 13:00:23,172] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 13:00:23,520] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform1, execution_date=20220412T125527, start_date=20220412T125911, end_date=20220412T130023
[2022-04-12 13:00:24,180] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 13:00:25,257] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
