[2022-04-11 14:17:41,982] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [queued]>
[2022-04-11 14:17:42,023] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [queued]>
[2022-04-11 14:17:42,026] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:17:42,027] {taskinstance.py:1250} INFO - Starting attempt 2 of 3
[2022-04-11 14:17:42,029] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:17:42,068] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:12:30.549249+00:00
[2022-04-11 14:17:42,077] {standard_task_runner.py:52} INFO - Started process 5399 to run task
[2022-04-11 14:17:42,085] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:12:30.549249+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpyuo9_vii', '--error-file', '/tmp/tmpt27oz8gu']
[2022-04-11 14:17:42,089] {standard_task_runner.py:80} INFO - Job 35: Subtask extract
[2022-04-11 14:17:42,243] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:17:42,441] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:12:30.549249+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:12:30.549249+00:00
[2022-04-11 14:20:11,660] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-11 14:20:11,747] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 5399. PIDs of all processes in the group: [5399]
[2022-04-11 14:20:11,769] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5399
[2022-04-11 14:20:11,785] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-11 14:20:13,907] {process_utils.py:70} INFO - Process psutil.Process(pid=5399, status='terminated', exitcode=0, started='14:17:41') (5399) terminated with exit code 0
