[2022-04-11 14:23:03,865] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [queued]>
[2022-04-11 14:23:04,105] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [queued]>
[2022-04-11 14:23:04,107] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:23:04,109] {taskinstance.py:1250} INFO - Starting attempt 4 of 6
[2022-04-11 14:23:04,111] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:23:04,220] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:12:30.549249+00:00
[2022-04-11 14:23:04,240] {standard_task_runner.py:52} INFO - Started process 5780 to run task
[2022-04-11 14:23:04,265] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:12:30.549249+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpxgskzcc0', '--error-file', '/tmp/tmp9rz0e6w5']
[2022-04-11 14:23:04,277] {standard_task_runner.py:80} INFO - Job 59: Subtask extract
[2022-04-11 14:23:05,600] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:23:06,557] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:12:30.549249+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:12:30.549249+00:00
[2022-04-11 14:23:10,177] {taskinstance.py:1037} INFO - Dependencies not met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-04-11 14:23:10,182] {taskinstance.py:1037} INFO - Dependencies not met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:12:30.549249+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-04-11 14:23:10,194] {local_task_job.py:99} INFO - Task is not able to be run
[2022-04-11 14:23:36,295] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-11 14:23:36,345] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 5780. PIDs of all processes in the group: [5780]
[2022-04-11 14:23:36,350] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5780
[2022-04-11 14:23:36,384] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-11 14:23:36,895] {process_utils.py:70} INFO - Process psutil.Process(pid=5780, status='terminated', exitcode=0, started='14:23:03') (5780) terminated with exit code 0
