[2022-04-12 12:48:47,136] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:47,220] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:47,227] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:47,229] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:48:47,231] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:47,299] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform4> on 2022-04-12 12:48:35.586771+00:00
[2022-04-12 12:48:47,316] {standard_task_runner.py:52} INFO - Started process 384 to run task
[2022-04-12 12:48:47,340] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform4', 'manual__2022-04-12T12:48:35.586771+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmpywego7yc', '--error-file', '/tmp/tmpokivus5s']
[2022-04-12 12:48:47,343] {standard_task_runner.py:80} INFO - Job 72: Subtask transform4
[2022-04-12 12:48:47,859] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:48:35.586771+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:48:48,577] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform4
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:48:35.586771+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:48:35.586771+00:00
[2022-04-12 12:49:26,149] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (11,15,32,38,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 12:50:02,213] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 12:50:02,440] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform4, execution_date=20220412T124835, start_date=20220412T124847, end_date=20220412T125002
[2022-04-12 12:50:03,327] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 12:50:04,290] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
