[2022-04-12 12:48:47,819] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:48,013] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:48:35.586771+00:00 [queued]>
[2022-04-12 12:48:48,022] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:48,024] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:48:48,028] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:48:48,219] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform1> on 2022-04-12 12:48:35.586771+00:00
[2022-04-12 12:48:48,252] {standard_task_runner.py:52} INFO - Started process 388 to run task
[2022-04-12 12:48:48,284] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform1', 'manual__2022-04-12T12:48:35.586771+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmpwcs5fn49', '--error-file', '/tmp/tmpfbcpf2t7']
[2022-04-12 12:48:48,299] {standard_task_runner.py:80} INFO - Job 74: Subtask transform1
[2022-04-12 12:48:48,943] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform1 manual__2022-04-12T12:48:35.586771+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:48:49,531] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform1
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:48:35.586771+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:48:35.586771+00:00
[2022-04-12 12:49:24,881] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (11,15,32,38,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 12:50:00,054] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 12:50:00,378] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform1, execution_date=20220412T124835, start_date=20220412T124847, end_date=20220412T125000
[2022-04-12 12:50:01,078] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 12:50:02,425] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
