[2022-04-12 12:59:13,999] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:59:14,128] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:59:14,134] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:59:14,138] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:59:14,141] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:59:14,337] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform4> on 2022-04-12 12:55:27.121131+00:00
[2022-04-12 12:59:14,371] {standard_task_runner.py:52} INFO - Started process 946 to run task
[2022-04-12 12:59:14,413] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform4', 'manual__2022-04-12T12:55:27.121131+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmpezm75rqd', '--error-file', '/tmp/tmpbd6h7pfc']
[2022-04-12 12:59:14,417] {standard_task_runner.py:80} INFO - Job 80: Subtask transform4
[2022-04-12 12:59:14,659] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform4 manual__2022-04-12T12:55:27.121131+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:59:15,257] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform4
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:55:27.121131+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:55:27.121131+00:00
[2022-04-12 12:59:52,493] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (10,14,31,37,39,40) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-12 13:00:20,761] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 13:00:21,063] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform4, execution_date=20220412T125527, start_date=20220412T125914, end_date=20220412T130021
[2022-04-12 13:00:21,885] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 13:00:23,014] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
